name: Go Release

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v0.1.0, v1.2.3

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'  # or your current version

      - name: Download Dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Trigger pkg.go.dev indexing
        run: |
          curl -X GET "https://proxy.golang.org/github.com/${{ github.repository | toLower }}/@v/${{ github.ref_name }}.info"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

